"""Last-run context file for workflow execution.

Writes and reads .workflow.last_run files that store the most recent
workflow execution context (workflow_id, run_id, etc.) so that
subsequent commands (status, input, review) can pick up from where
the run command left off.

File format (.workflow.last_run):
    # Auto-generated by workflow CLI. Do not edit manually.
    workflow_id: 939843a8-6257-4475-bfc0-f7d6500d9f00
    run_id: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    instance: https://stage.sb.allogy.com
    started_at: 2026-02-25T10:30:00+00:00
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from uuid import UUID

import yaml
from pydantic import BaseModel, Field

LAST_RUN_FILENAME = '.workflow.last_run'
LAST_RUN_HEADER = '# Auto-generated by workflow CLI. Do not edit manually.\n'


class LastRunContext(BaseModel):
    """Schema for .workflow.last_run file."""

    workflow_id: UUID = Field(..., description='Workflow UUID that was executed')
    run_id: str = Field(..., description='Run ID returned by the platform')
    instance: str = Field(..., description='API host URL used for this run')
    started_at: datetime = Field(..., description='Timestamp when the run was started')


def save_last_run(directory: Path, context: LastRunContext) -> Path:
    """Write a .workflow.last_run file to the given directory.

    Args:
        directory: Directory to write the file in.
        context: Run context to persist.

    Returns:
        Path to the written file.
    """
    path = directory / LAST_RUN_FILENAME
    data = {
        'workflow_id': str(context.workflow_id),
        'run_id': context.run_id,
        'instance': context.instance,
        'started_at': context.started_at.isoformat(),
    }
    with path.open('w') as f:
        f.write(LAST_RUN_HEADER)
        yaml.safe_dump(data, f, default_flow_style=False, sort_keys=False)
    return path


def load_last_run(directory: Path) -> LastRunContext | None:
    """Load a .workflow.last_run file from the given directory.

    Args:
        directory: Directory to look for the file in.

    Returns:
        LastRunContext if the file exists and is valid, None otherwise.
    """
    path = directory / LAST_RUN_FILENAME
    if not path.exists():
        return None

    try:
        content = path.read_text()
        lines = [line for line in content.split('\n') if not line.strip().startswith('#')]
        data = yaml.safe_load('\n'.join(lines))

        if not isinstance(data, dict):
            return None

        return LastRunContext(
            workflow_id=UUID(data['workflow_id']),
            run_id=data['run_id'],
            instance=data['instance'],
            started_at=datetime.fromisoformat(data['started_at']),
        )
    except (KeyError, ValueError, TypeError):
        return None
