"""Lockfile management for workflow push operations.

The lockfile (.workflow.lock) tracks the mapping between local slugs and
server-side UUIDs to enable idempotent push operations (updates instead of
creating duplicates).

Lockfile format (.workflow.lock):
    # Auto-generated by workflow CLI. Do not edit manually.
    workflow_id: 3fa85f64-5717-4562-b3fc-2c963f66afa6
    organization_id: 9a8b7c6d-5e4f-3a2b-1c0d-9e8f7a6b5c4d
    version: 1
    instance: https://api.sb.allogy.com
    nodes:
      upload: a1b2c3d4-e5f6-7890-abcd-ef1234567890
      extract: b2c3d4e5-f6a7-8901-bcde-f12345678901
    edges:
      upload->extract: 1001
    pushed_at: 2026-02-15T14:30:00Z
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any
from uuid import UUID

import yaml
from pydantic import BaseModel, Field, field_validator

LOCKFILE_VERSION = 1
LOCKFILE_HEADER = '# Auto-generated by workflow CLI. Do not edit manually.\n'


class WorkflowLock(BaseModel):
    """Schema for .workflow.lock file.

    Tracks the mapping between local slugs and server-side UUIDs for
    idempotent push operations.
    """

    workflow_id: UUID = Field(..., description='Server-side workflow UUID')
    organization_id: UUID = Field(..., description='Organization UUID')
    version: int = Field(default=LOCKFILE_VERSION, description='Lockfile schema version')
    instance: str = Field(..., description='API host URL (e.g., https://api.sb.allogy.com)')
    nodes: dict[str, UUID] = Field(
        default_factory=dict, description='Mapping of node slug to server-side UUID'
    )
    edges: dict[str, int] = Field(
        default_factory=dict,
        description='Mapping of edge key (source->target) to server-side edge ID',
    )
    dependencies: dict[str, UUID] = Field(
        default_factory=dict,
        description=(
            'Cached dependency name-to-UUID mappings from previous push. '
            "Keys are in the format 'agent:{name}' or 'kb:{name}'."
        ),
    )
    pushed_at: datetime = Field(..., description='Timestamp of last successful push')

    @field_validator('version')
    @classmethod
    def validate_version(cls, v: int) -> int:
        """Validate that the lockfile version is supported."""
        if v != LOCKFILE_VERSION:
            msg = f'Unsupported lockfile version: {v}. Expected {LOCKFILE_VERSION}'
            raise ValueError(msg)
        return v

    @field_validator('instance')
    @classmethod
    def validate_instance(cls, v: str) -> str:
        """Validate that the instance URL is not empty."""
        if not v or not v.strip():
            msg = 'Instance URL cannot be empty'
            raise ValueError(msg)
        return v.strip()

    def to_yaml_dict(self) -> dict[str, Any]:
        """Convert to a YAML-serializable dictionary.

        UUID fields are converted to strings for YAML serialization.
        """
        data: dict[str, Any] = {
            'workflow_id': str(self.workflow_id),
            'organization_id': str(self.organization_id),
            'version': self.version,
            'instance': self.instance,
            'nodes': {slug: str(uuid) for slug, uuid in self.nodes.items()},
            'edges': self.edges.copy(),
        }
        if self.dependencies:
            data['dependencies'] = {key: str(uuid) for key, uuid in self.dependencies.items()}
        data['pushed_at'] = self.pushed_at.isoformat()
        return data

    @classmethod
    def from_yaml_dict(cls, data: dict[str, Any]) -> WorkflowLock:
        """Create from a YAML-loaded dictionary.

        UUID strings are converted to UUID objects.

        Raises:
            ValueError: If required fields are missing or invalid.
        """
        try:
            return cls(
                workflow_id=UUID(data['workflow_id']),
                organization_id=UUID(data['organization_id']),
                version=data['version'],
                instance=data['instance'],
                nodes={slug: UUID(uuid_str) for slug, uuid_str in data.get('nodes', {}).items()},
                edges=data.get('edges', {}),
                dependencies={
                    key: UUID(uuid_str) for key, uuid_str in data.get('dependencies', {}).items()
                },
                pushed_at=datetime.fromisoformat(data['pushed_at']),
            )
        except (KeyError, TypeError) as e:
            msg = f'Invalid lockfile schema: {e}'
            raise ValueError(msg) from e

    def get_node_uuid(self, slug: str) -> UUID | None:
        """Get the server-side UUID for a node slug, or None if not found."""
        return self.nodes.get(slug)

    def get_edge_id(self, source_slug: str, target_slug: str) -> int | None:
        """Get the server-side edge ID for a source->target pair, or None if not found."""
        edge_key = f'{source_slug}->{target_slug}'
        return self.edges.get(edge_key)

    def set_node_uuid(self, slug: str, uuid: UUID) -> None:
        """Set or update the server-side UUID for a node slug."""
        self.nodes[slug] = uuid

    def set_edge_id(self, source_slug: str, target_slug: str, edge_id: int) -> None:
        """Set or update the server-side edge ID for a source->target pair."""
        edge_key = f'{source_slug}->{target_slug}'
        self.edges[edge_key] = edge_id

    def remove_node(self, slug: str) -> bool:
        """Remove a node mapping. Returns True if removed, False if not found."""
        if slug in self.nodes:
            del self.nodes[slug]
            return True
        return False

    def remove_edge(self, source_slug: str, target_slug: str) -> bool:
        """Remove an edge mapping. Returns True if removed, False if not found."""
        edge_key = f'{source_slug}->{target_slug}'
        if edge_key in self.edges:
            del self.edges[edge_key]
            return True
        return False


def get_lockfile_path(workflow_path: Path) -> Path:
    """Get the lockfile path for a given workflow file.

    The lockfile is in the same directory as the workflow file, with the
    same base name but .lock extension.

    Examples:
        /path/to/my.workflow.yaml -> /path/to/my.workflow.lock
        /path/to/workflow.yaml -> /path/to/workflow.lock
    """
    if workflow_path.suffix == '.yaml':
        # Remove .yaml and add .lock
        return workflow_path.with_suffix('.lock')
    # If no .yaml suffix, just add .lock
    return Path(str(workflow_path) + '.lock')


def read_lockfile(lockfile_path: Path) -> WorkflowLock:
    """Read and parse a lockfile from disk.

    Args:
        lockfile_path: Path to the .workflow.lock file.

    Returns:
        WorkflowLock instance with the parsed lockfile data.

    Raises:
        FileNotFoundError: If the lockfile does not exist.
        yaml.YAMLError: If the lockfile contains invalid YAML.
        ValueError: If the lockfile schema is invalid.
    """
    if not lockfile_path.exists():
        msg = f'Lockfile not found: {lockfile_path}'
        raise FileNotFoundError(msg)

    with lockfile_path.open('r') as f:
        # Skip header comment lines
        content = f.read()
        # Remove header comment before parsing YAML
        lines = content.split('\n')
        yaml_lines = [line for line in lines if not line.strip().startswith('#')]
        yaml_content = '\n'.join(yaml_lines)

        data = yaml.safe_load(yaml_content)

    if not isinstance(data, dict):
        msg = f'Invalid lockfile format: expected dict, got {type(data)}'
        raise ValueError(msg)

    return WorkflowLock.from_yaml_dict(data)


def write_lockfile(lockfile_path: Path, lock: WorkflowLock) -> None:
    """Write a lockfile to disk.

    Creates parent directories if needed. Overwrites existing file.

    Args:
        lockfile_path: Path to the .workflow.lock file.
        lock: WorkflowLock instance to write.
    """
    # Create parent directories if needed
    lockfile_path.parent.mkdir(parents=True, exist_ok=True)

    with lockfile_path.open('w') as f:
        # Write header comment
        f.write(LOCKFILE_HEADER)
        # Write YAML data
        yaml.safe_dump(lock.to_yaml_dict(), f, default_flow_style=False, sort_keys=False)


def load_lockfile(lockfile_path: Path) -> WorkflowLock | None:
    """Load a lockfile if it exists, otherwise return None.

    This is a convenience wrapper around read_lockfile that returns None
    instead of raising FileNotFoundError.

    Args:
        lockfile_path: Path to the .workflow.lock file.

    Returns:
        WorkflowLock instance if the file exists, otherwise None.

    Raises:
        yaml.YAMLError: If the lockfile contains invalid YAML.
        ValueError: If the lockfile schema is invalid.
    """
    try:
        return read_lockfile(lockfile_path)
    except FileNotFoundError:
        return None


def save_lockfile(workflow_path: Path, lock: WorkflowLock) -> None:
    """Save a lockfile alongside a workflow file.

    Args:
        workflow_path: Path to the .workflow.yaml file.
        lock: WorkflowLock instance to save.
    """
    lockfile_path = get_lockfile_path(workflow_path)
    write_lockfile(lockfile_path, lock)


def update_lockfile(lockfile_path: Path, lock: WorkflowLock) -> None:
    """Update an existing lockfile in place.

    This is an alias for write_lockfile, provided for semantic clarity
    when the intent is to update rather than create.

    Args:
        lockfile_path: Path to the .workflow.lock file.
        lock: WorkflowLock instance with updated data.
    """
    write_lockfile(lockfile_path, lock)


def remove_lockfile(lockfile_path: Path) -> None:
    """Remove a lockfile from disk.

    Does not raise an error if the file does not exist.

    Args:
        lockfile_path: Path to the .workflow.lock file to remove.
    """
    lockfile_path.unlink(missing_ok=True)
